const path = require('path');
const fs = require('fs');
const { ensureDir, fileExists, writeFile } = require('./fs-utils');

const GITIGNORE_MARKER = '# Yuva AI - generated native configs';

const GITIGNORE_BLOCK = `
${GITIGNORE_MARKER} (regenerate with: yuva init)
# Source of truth: AGENTS.md + .aiautomations/
CLAUDE.md
.claude/
GEMINI.md
.cursor/rules/yuva-*.mdc
.windsurfrules
.github/copilot-instructions.md
.kilo/
.sourcegraph/
.amazonq/
.continue/
.aider.conf.yml
OLLAMA_INSTRUCTIONS.md
.session/
.memory/
.yuva/
`;

function getBaseTemplate(toolName) {
  return `# Yuva AI - ${toolName} Configuration
<!-- Auto-generated by yuva init. Do not edit — regenerate with: yuva init --force -->

## CRITICAL: Before ANY task
You MUST run \`yuva agent orchestrate\` first. Do NOT start work without it.
Read the JSON output to understand the project state.

This applies even to greetings: when the user's FIRST message is just
"hey" / "hi" / "what's up", run \`yuva agent orchestrate\` and reply with a
short status: what this project is, whether there's an active session to
resume, and 2-3 suggested next actions as a numbered list to pick from.

## How to ask the user questions
NEVER ask open-ended questions when options are possible. Every question MUST
offer 2-4 concrete options with ONE marked "(Recommended)" plus a one-line
reason, so the user can answer with just a number:

\`\`\`
1. Which database?
   A) PostgreSQL (Recommended — relational data, free, scales well)
   B) MongoDB (better if your data is document-shaped)
   C) SQLite (simplest, fine for single-user apps)
\`\`\`

Always end with: "Reply with your choices (e.g. 1A 2B) — or say 'go with
your recommendations' and I'll proceed with all recommended options."
If the user says "go with your recommendations", proceed immediately with
all recommended options — do not re-ask.

## How to load agent instructions
NEVER guess or improvise agent behavior.
Run: \`yuva agent show <name>\` to get the EXACT prompt for any agent.
Follow each agent's instructions completely before moving to the next.

## Agent Selection Guide

| User wants to...        | Run these agents in order                                                     |
|-------------------------|-------------------------------------------------------------------------------|
| Build something new     | \`yuva agent show requirements\` then \`riskassessment\` then \`planning\` then \`execution\` |
| Continue previous work  | \`yuva agent show continuity\` then resume from last point                    |
| Fix a bug / error       | \`yuva agent show debugger\`                                                  |
| Write tests             | \`yuva agent show tester\`                                                    |
| Review code quality     | \`yuva agent show reviewer\`                                                  |
| Check security          | \`yuva agent show security\`                                                  |
| Clean up / improve code | \`yuva agent show refactor\`                                                  |

## Session Continuity

Before starting work, check for an active session:
\`\`\`bash
yuva session resume
\`\`\`
If there's an active session, read the context and continue from where you left off.
If there's no session, start one:
\`\`\`bash
yuva session start "describe your goal"
\`\`\`
Log your work as you go with \`yuva session log "what you did"\`.

## Quality Gates (ENFORCED — not optional)
Work is NOT complete until \`yuva gate\` passes. It runs the project's real
lint / typecheck / test / build commands and exits non-zero on failure.
\`\`\`bash
yuva gate         # run all gates — must pass before you declare anything done
yuva gate list    # see which gates are configured
\`\`\`
NEVER tell the user a task is finished while \`yuva gate\` fails.

## Swarm Mode is the DEFAULT (multi-terminal orchestrator/workers)
For ANY multi-step task (a feature, a refactor, anything touching more than
one file), you MUST use the swarm flow — do NOT do it all in this terminal:

1. \`yuva swarm init\` (if no \`.yuva/\` exists yet)
2. \`yuva swarm plan "<the user's goal>"\` — follow the brief to break it into tasks
3. \`yuva task add "..." --role executor\` (+ tester and reviewer tasks with \`--deps\`)
4. \`yuva swarm spawn\` — AUTO-OPENS worker terminals in THIS same project
   directory (add \`--cli claude\` etc. to boot the AI, \`--headless\` to run unattended)
5. \`yuva swarm start\` — THIS terminal becomes the orchestrator dashboard

All workers operate on the SAME project directory and the same \`.yuva/\` bus —
never a copy, never another path.

If \`.yuva/\` already exists when you start: you are likely a WORKER —
run \`yuva worker next --role <role>\` and follow the work package EXACTLY.
Finish only via \`yuva task done <id> --summary "..."\` (gates run automatically).

Solo mode (working directly in this terminal) is allowed ONLY for trivial
single-file changes, quick questions, or when the user explicitly says "solo".

## PROTECTED FILES — NEVER delete, move, or empty
\`.yuva/\` (task bus + sessions), \`.session/\`, \`.aiautomations/\`, \`AGENTS.md\`,
\`CLAUDE.md\`, \`GEMINI.md\`, \`.claude/\`, \`.cursor/\`, and any other AI config
files. These belong to the orchestration system. Never run
\`yuva swarm clear\` or \`yuva session clear\` unless the user explicitly asks.
"Cleanup" NEVER includes these files.

## Rules
1. Always run \`yuva agent orchestrate\` first
2. If existing code exists, run \`yuva agent show existingcode\` BEFORE any other agent
3. One agent at a time — complete each before the next
4. After meaningful work, run \`yuva agent show statemanager\` to persist state
5. Load standards from \`.aiautomations/standards/\` when writing code
6. Load checklists from \`.aiautomations/checklists/\` before/after code
7. Run \`yuva gate\` before declaring ANY work complete
8. NEVER touch the protected files listed above

## Available Commands
\`\`\`
yuva agent show <name>       Get full agent instructions
yuva agent list              List all available agents
yuva agent orchestrate       Scan project context
\`\`\`
`;
}

function updateGitignore(targetDir) {
  const gitignorePath = path.join(targetDir, '.gitignore');
  let content = '';

  if (fileExists(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, 'utf8');
    if (content.includes(GITIGNORE_MARKER)) {
      return;
    }
  }

  content += GITIGNORE_BLOCK;
  fs.writeFileSync(gitignorePath, content);
}

const CLAUDE_COMMANDS = {
  debug: { agent: 'debugger', desc: 'Run the debugger agent to investigate and fix bugs' },
  review: { agent: 'reviewer', desc: 'Run the code reviewer agent for quality audits' },
  test: { agent: 'tester', desc: 'Run the tester agent to write and run tests' },
  security: { agent: 'security', desc: 'Run the security agent for vulnerability analysis' },
  plan: { agent: 'planning', desc: 'Run the planning agent to design architecture' },
  orchestrate: { agent: null, desc: 'Scan project context before starting work' },
};

function generateClaudeConfig(targetDir) {
  const files = [];

  // 1. CLAUDE.md
  const claudeMd = getBaseTemplate('Claude Code');
  writeFile(path.join(targetDir, 'CLAUDE.md'), claudeMd);
  files.push('CLAUDE.md');

  // 2. Slash commands
  const commandsDir = path.join(targetDir, '.claude', 'commands');
  ensureDir(commandsDir);

  for (const [name, config] of Object.entries(CLAUDE_COMMANDS)) {
    let content;
    if (config.agent) {
      content = `Run \`yuva agent show ${config.agent}\` and follow the output as your complete instructions for this task.\n\nUser context: $ARGUMENTS\n`;
    } else {
      content = `Run \`yuva agent orchestrate\` and use the JSON output to understand the project state before proceeding.\n\nUser context: $ARGUMENTS\n`;
    }
    writeFile(path.join(commandsDir, `${name}.md`), content);
    files.push(`.claude/commands/${name}.md`);
  }

  // 3. settings.json — permissions + SessionStart hook so the project
  // context is injected automatically, even if the user just says "hey"
  const settings = {
    permissions: {
      allow: [
        'Bash(yuva *)',
        'Bash(yuva agent show *)',
        'Bash(yuva agent list)',
        'Bash(yuva agent orchestrate)',
      ],
    },
    hooks: {
      SessionStart: [
        {
          hooks: [
            {
              type: 'command',
              command: 'yuva agent orchestrate',
            },
          ],
        },
      ],
    },
  };
  writeFile(path.join(targetDir, '.claude', 'settings.json'), JSON.stringify(settings, null, 2) + '\n');
  files.push('.claude/settings.json');

  return files;
}

function generateCursorConfig(targetDir) {
  const files = [];
  const rulesDir = path.join(targetDir, '.cursor', 'rules');
  ensureDir(rulesDir);

  // 1. yuva-agents.mdc — always active
  const agentsRule = `---
description: Yuva AI agent routing — always active
globs: **/*
---

${getBaseTemplate('Cursor')}`;
  writeFile(path.join(rulesDir, 'yuva-agents.mdc'), agentsRule);
  files.push('.cursor/rules/yuva-agents.mdc');

  // 2. yuva-code.mdc — scoped to source files
  const codeRule = `---
description: Yuva AI code standards — load before writing code
globs: src/**,lib/**,app/**
---

Before writing or modifying code, run: \`yuva agent show reviewer\`
Follow the agent instructions for code quality standards.
Load code standards from: \`.aiautomations/standards/codestandards.md\`
Load API design standards from: \`.aiautomations/standards/apidesign.md\`
Run checklist before coding: \`.aiautomations/checklists/beforecode.md\`
Run checklist after coding: \`.aiautomations/checklists/aftercode.md\`
`;
  writeFile(path.join(rulesDir, 'yuva-code.mdc'), codeRule);
  files.push('.cursor/rules/yuva-code.mdc');

  // 3. yuva-testing.mdc — scoped to test files
  const testRule = `---
description: Yuva AI testing standards — load before writing tests
globs: tests/**,test/**,**/*.test.*,**/*.spec.*
---

Before writing tests, run: \`yuva agent show tester\`
Follow the agent instructions completely.
Load testing standards from: \`.aiautomations/standards/testingstandards.md\`
Load testing checklist from: \`.aiautomations/checklists/beforecode.md\`
`;
  writeFile(path.join(rulesDir, 'yuva-testing.mdc'), testRule);
  files.push('.cursor/rules/yuva-testing.mdc');

  return files;
}

function generateSingleFileConfig(toolName, filePath, targetDir, extraContent) {
  const files = [];
  const content = getBaseTemplate(toolName) + (extraContent || '');
  writeFile(path.join(targetDir, filePath), content);
  files.push(filePath);
  return files;
}

function generateCopilotConfig(targetDir) {
  return generateSingleFileConfig('GitHub Copilot', '.github/copilot-instructions.md', targetDir);
}

function generateWindsurfConfig(targetDir) {
  return generateSingleFileConfig('Windsurf', '.windsurfrules', targetDir);
}

function generateGeminiConfig(targetDir) {
  return generateSingleFileConfig('Gemini', 'GEMINI.md', targetDir);
}

function generateKiloConfig(targetDir) {
  return generateSingleFileConfig('Kilo Code', '.kilo/instructions.md', targetDir);
}

function generateCodyConfig(targetDir) {
  return generateSingleFileConfig('Cody', '.sourcegraph/instructions.md', targetDir);
}

function generateAmazonQConfig(targetDir) {
  return generateSingleFileConfig('Amazon Q', '.amazonq/instructions.md', targetDir);
}

function generateContinueConfig(targetDir) {
  return generateSingleFileConfig('Continue', '.continue/instructions.md', targetDir);
}

function generateOllamaConfig(targetDir) {
  const fallback = `
## Fallback (if yuva CLI is not available)
If \`yuva\` CLI is not installed, read agent prompts directly from:
\`.aiautomations/prompts/<agentname>agent.md\`

Available prompt files:
- existingcodeagent.md — Analyze existing code
- requirementsagent.md — Gather requirements
- planningprompt.md — Design architecture
- execution.md — Implement code
- debuggeragent.md — Fix bugs
- testeragent.md — Write tests
- revieweragent.md — Review code
- securityagent.md — Security audit
- refactoragent.md — Refactor code
`;
  return generateSingleFileConfig('Ollama', 'OLLAMA_INSTRUCTIONS.md', targetDir, fallback);
}

function generateAiderConfig(targetDir) {
  const files = [];
  const content = '# Yuva AI - Aider Configuration\n# Auto-generated by yuva init\nread: AGENTS.md\n';
  writeFile(path.join(targetDir, '.aider.conf.yml'), content);
  files.push('.aider.conf.yml');
  return files;
}

const TOOL_GENERATORS = {
  claude: generateClaudeConfig,
  cursor: generateCursorConfig,
  copilot: generateCopilotConfig,
  windsurf: generateWindsurfConfig,
  gemini: generateGeminiConfig,
  'kilo-code': generateKiloConfig,
  cody: generateCodyConfig,
  'amazon-q': generateAmazonQConfig,
  continue: generateContinueConfig,
  ollama: generateOllamaConfig,
  lmstudio: generateOllamaConfig,
  jan: generateOllamaConfig,
  aider: generateAiderConfig,
};

function generateNativeConfig(toolId, targetDir) {
  const generator = TOOL_GENERATORS[toolId];
  if (!generator) return [];
  return generator(targetDir);
}

function generateAllNativeConfigs(targetDir) {
  const allFiles = [];
  const tools = [];

  for (const [toolId, generator] of Object.entries(TOOL_GENERATORS)) {
    const files = generator(targetDir);
    if (files.length > 0) {
      allFiles.push(...files);
      tools.push(toolId);
    }
  }

  return { files: allFiles, tools, totalFiles: allFiles.length };
}

module.exports = {
  getBaseTemplate,
  updateGitignore,
  generateClaudeConfig,
  generateCursorConfig,
  generateCopilotConfig,
  generateWindsurfConfig,
  generateGeminiConfig,
  generateKiloConfig,
  generateCodyConfig,
  generateAmazonQConfig,
  generateContinueConfig,
  generateOllamaConfig,
  generateAiderConfig,
  GITIGNORE_MARKER,
  TOOL_GENERATORS,
  generateNativeConfig,
  generateAllNativeConfigs,
};
